# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Screw Cutter Project
tagline:          'Recent News'
description:      ''
url:              http://blog.screwcutter.com
baseurl:          '/'
paginate:         3

author:
  name:           'Gregory Allan'
  url:            https://twitter.com/greg2differ

# Custom vars
version:          1.0.0

github:
  repo:           
